ignores:
  - '@repobuddy/jest' # depcheck doesn't recognize jest plugins/presets
  - '@size-limit/*' # depcheck doesn't recognize size-limit plugins
  - '@types/*'
  - 'eslint*' # hoisted to the root of the repo
  - rimraf # used by the `clean` script, which depcheck does not read
  - jest-* # depcheck doesn't recognize jest plugins/presets
  - ts-jest # depcheck doesn't recognize jest plugins
