/**
 * `<ESC>` represents the ASCII "escape" character, 0x1B.
 */
export const ESCAPE = '\x1b'
/**
 * Requests a `Report Device Code` response from the device.
 */
export const QUERY_DEVICE_CODE = '[c'

/**
 * Generated by the device in response to `Query Device Code` request.
 */
export const REPORT_DEVICE_CODE_EX = /\[(\w+)0c(.*)/
/**
 * Requests a `Report Device Status` response from the device.
 */
export const QUERY_DEVICE_STATUS = '[5n'
/**
 * Generated by the device in response to a `Query Device Status` request; indicates that device is functioning correctly.
 */
export const REPORT_DEVICE_OK = '[0n'
/**
 * Generated by the device in response to the `Query Device Status` request;
 * indicates that device is functioning improperly.
 */
export const REPORT_DEVICE_FAILURE = '[3n'

export const RESET = '[0m'
export const BOLD = '[1m'
export const UNDERLINE = '[4m'
export const INVERSE = '[7m'
export const BLACK = '[30m'
export const RED = '[31m'
export const GREEN = '[32m'
export const YELLOW = '[33m'
export const BLUE = '[34m'
export const MAGENTA = '[35m'
export const CYAN = '[36m'
export const WHITE = '[37m'
export const GRAY = '[90m'
export const LIGHT_RED = '[91m'
export const LIGHT_GREEN = '[92m'
export const LIGHT_YELLOW = '[93m'
export const LIGHT_BLUE = '[94m'
export const LIGHT_MAGENTA = '[95m'
export const LIGHT_CYAN = '[96m'
export const LIGHT_WHITE = '[97m'
